### ISSUE TITLE
Which format to use for the source file?

### ISSUE THREAD

**Issue by jdblischak** [jdblischak/ctv-project-workflows#1]
The source file is currently written in Markdown. This is convenient for viewing online on GitHub. For submission, we need it to be in CTV format (explained in the [ctv package vignette](https://cran.r-project.org/web/packages/ctv/vignettes/ctv-howto.pdf)). I think we want to maintain both formats. It just a matter of which one will be the source and which one will be automatically generated.

Options:
1. Edit Markdown. Generate CTV.
2. Edit CTV. Generate Markdown.
3. Other suggestion

**Comment by jdblischak** [comment]
The recently accepted task view [MissingData](https://cran.r-project.org/view=MissingData) uses a [ctv file](https://github.com/R-miss-tastic/missing-data-taskview/blob/master/source/MissingData.ctv) as the source and then generates HTML using the ctv package.

**Comment by jdblischak** [comment]
@benmarwick @nuest Both of your task views use a Markdown file as source (for my future reference: [here](https://github.com/benmarwick/ctv-archaeology/blob/master/README.md) and [here](https://github.com/o2r-project/ctv-computational-environments/blob/master/compenv.md), respectively). Would you prefer to also use a Markdown-based workflow for this repository?

**Comment by jdblischak** [comment]
@benmarwick @nuest Thoughts on the build process for the task view?

**Comment by benmarwick** [comment]
Yes I think markdown is much more user friendly and inviting for contributors of any skill level

**Comment by jdblischak** [comment]
The source file is [ProjectWorkflows.md](https://github.com/jdblischak/ctv-project-workflows/blob/master/ProjectWorkflows.md). I've updated [CONTRIBUTING.md](https://github.com/jdblischak/ctv-project-workflows/blob/master/.github/CONTRIBUTING.md) to instruct potential contributors to edit this file.

For maintainers, the script [build.R](https://github.com/jdblischak/ctv-project-workflows/blob/master/build.R) can be run to convert the Markdown file to CTV and HTML.

Also, the HTML file is hosted on GitHub Pages at https://jdblischak.github.io/ctv-project-workflows/
